url: https://zahlenhelfer.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Zahlenhelfer Training & Consulting
email: website@zahlenhelfer.de
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'

# header-settings
header-line-1: Welcome to my Website!
header-line-2: Let´s try "cloudy" things
header-button: Tell Me More

# services
services-opener: Lorem ipsum dolor sit amet consectetur.
services-left-header: Cloud Trainings
services-left-text: Started with AWS, followed by Azure and now Google.
services-mid-header: Cloud Native Tooling
services-mid-text: I felt in love with Terraform
services-right-header: Kubernetes Eco-System
services-right-text: I´m so thrilled to work as an Linuxfoundation Trainer

# portfolio

# Team names, titles and social links
people:
  - name: Marcus Ross
    pic: 2
    position: Chief Cloud Executive
    social:
      - title: twitter
        url: http://twitter.com/zahlenhelfer
      - title: linkedin
        url:
      - title: instagram
        url: https://www.instagram.com/zahlenhelfer/
      - title: bitbucket
        url: http://bitbucket.org/zahlenhelfer
      - title: github
        url: http://github.com/zahlenhelfer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zahlenhelfer
  - title: linkedin
    url:
  - title: instagram
    url: https://www.instagram.com/zahlenhelfer/
  - title: bitbucket
    url: http://bitbucket.org/zahlenhelfer
  - title: github
    url: http://github.com/zahlenhelfer

# Postal address (add as many lines as necessary)
address:
  - line: Elisenstrasse 14a
  - line: 21244 Buchholz, Germany

# Build settings
markdown: kramdown
permalink: pretty
